import api from "@/lib/axios";
export const getWorkspace = () => api.get("/workspace/bootstrap");
export const searchWorkspace = (q:string) => api.get("/search",{params:{q}});
export const getOverview = () => api.get("/dashboard/overview");
export const getWorkTasks = (params:Record<string,unknown>={}) => api.get("/tasks",{params});
export const getTask = (id:number|string) => api.get(`/tasks/${id}`);
export const createTask = (data:unknown) => api.post("/tasks",data);
export const updateTask = (id:number|string,data:unknown) => api.patch(`/tasks/${id}`,data);
export const reorderTasks = (items:{id:number;status?:string;position:number}[]) => api.post("/tasks/reorder",{items});
export const addComment = (id:number,body:string) => api.post(`/tasks/${id}/comments`,{body});
export const addChecklist = (id:number,title:string) => api.post(`/tasks/${id}/checklist`,{title});
export const updateChecklist = (taskId:number,itemId:number,data:unknown) => api.patch(`/tasks/${taskId}/checklist/${itemId}`,data);
export const deleteChecklist = (taskId:number,itemId:number) => api.delete(`/tasks/${taskId}/checklist/${itemId}`);
export const watchTask = (id:number) => api.post(`/tasks/${id}/watch`);
export const unwatchTask = (id:number) => api.delete(`/tasks/${id}/watch`);
export const addDependency = (id:number,depends_on_task_id:number,type="blocks") => api.post(`/tasks/${id}/dependencies`,{depends_on_task_id,type});
export const uploadAttachment = (id:number,file:File) => { const form=new FormData();form.append("file",file);return api.post(`/tasks/${id}/attachments`,form,{headers:{"Content-Type":"multipart/form-data"}}); };
export const startTimer = (id:number) => api.post(`/tasks/${id}/timer/start`);
export const stopTimer = (id:number) => api.post(`/tasks/${id}/timer/stop`);
export const addTime = (id:number,duration_minutes:number,note?:string) => api.post(`/tasks/${id}/time`,{duration_minutes,note});
export const getNotifications = (unread=false) => api.get("/notifications",{params:{unread}});
export const readNotification = (id:number) => api.patch(`/notifications/${id}/read`);
export const readAllNotifications = () => api.post("/notifications/read-all");
export const getActivity = (page=1) => api.get("/activity",{params:{page}});
export const createLabel = (data:{project_id?:number|null;name:string;color:string}) => api.post("/labels",data);
export const deleteLabel = (id:number) => api.delete(`/labels/${id}`);
export const downloadAttachment = (taskId:number,attachmentId:number) => api.get(`/tasks/${taskId}/attachments/${attachmentId}`,{responseType:"blob"});

export const getSavedViews = () => api.get("/saved-views");
export const createSavedView = (data:{name:string;scope:"tasks"|"projects";filters:Record<string,unknown>;is_default?:boolean}) => api.post("/saved-views",data);
export const deleteSavedView = (id:number) => api.delete(`/saved-views/${id}`);
