"use client";
import {useEffect,useState} from "react";
import {getDepartments} from "@/services/departmentService";
import {getWorkspace} from "@/services/workService";
import type {Workspace} from "@/lib/workTypes";

const colors=["#635bff","#377cf6","#16a36f","#d97706","#dc3445","#8b5cf6","#0f9f9a","#64748b"];
export type ProjectValues={name:string;key?:string;description?:string;color?:string;status:string;priority:string;health:string;visibility:string;start_date?:string;due_date?:string;department_id?:string;owner_id?:string;member_ids:number[]};
const defaults:ProjectValues={name:"",key:"",description:"",color:colors[0],status:"planning",priority:"medium",health:"on_track",visibility:"team",start_date:"",due_date:"",department_id:"",owner_id:"",member_ids:[]};
export default function ProjectForm({initial,onSubmit,submitLabel}:{initial?:Partial<ProjectValues>;onSubmit:(v:ProjectValues)=>Promise<void>;submitLabel:string}){
 const [v,setV]=useState<ProjectValues>({...defaults,...initial,member_ids:initial?.member_ids||[]});const [ws,setWs]=useState<Workspace|null>(null),[departments,setDepartments]=useState<any[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{Promise.all([getWorkspace(),getDepartments({per_page:100})]).then(([w,d])=>{setWs(w.data);setDepartments(d.data.data||[])})},[]);
 useEffect(()=>{if(initial)setV({...defaults,...initial,member_ids:initial.member_ids||[]})},[initial]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await onSubmit(v)}catch(err:any){setError(err?.response?.data?.message||"Could not save project.")}finally{setBusy(false)}};
 return <form className="advanced-project-form" onSubmit={save}>{error&&<div className="inline-error">{error}</div>}<div className="project-form-grid"><section className="project-form-main">
  <div className="form-section-head"><span className="eyebrow">Basics</span><h2>Project identity</h2><p>Give the work a clear name and enough context for anyone joining later.</p></div>
  <label className="field-label">Project name<input className="modern-input" value={v.name} onChange={e=>setV({...v,name:e.target.value})} placeholder="Website redesign" required/></label>
  <div className="composer-grid"><label className="field-label">Project key<input className="modern-input" value={v.key||""} onChange={e=>setV({...v,key:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,12)})} placeholder="WEB"/></label><label className="field-label">Department<select className="modern-input" value={v.department_id||""} onChange={e=>setV({...v,department_id:e.target.value})}><option value="">No department</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div>
  <label className="field-label">Description<textarea className="modern-textarea project-description" value={v.description||""} onChange={e=>setV({...v,description:e.target.value})} placeholder="What outcome should this project deliver? Add scope, goals and important constraints."/></label>
  <div className="form-section-head second"><span className="eyebrow">Delivery</span><h2>Planning signals</h2></div>
  <div className="composer-grid"><label className="field-label">Status<select className="modern-input" value={v.status} onChange={e=>setV({...v,status:e.target.value})}><option value="planning">Planning</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></label><label className="field-label">Priority<select className="modern-input" value={v.priority} onChange={e=>setV({...v,priority:e.target.value})}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></label><label className="field-label">Health<select className="modern-input" value={v.health} onChange={e=>setV({...v,health:e.target.value})}><option value="on_track">On track</option><option value="at_risk">At risk</option><option value="off_track">Off track</option></select></label><label className="field-label">Visibility<select className="modern-input" value={v.visibility} onChange={e=>setV({...v,visibility:e.target.value})}><option value="team">Team</option><option value="private">Private</option></select></label><label className="field-label">Start date<input type="date" className="modern-input" value={v.start_date||""} onChange={e=>setV({...v,start_date:e.target.value})}/></label><label className="field-label">Due date<input type="date" className="modern-input" value={v.due_date||""} onChange={e=>setV({...v,due_date:e.target.value})}/></label></div>
 </section><aside className="project-form-side"><div className="form-section-head"><span className="eyebrow">Ownership</span><h2>People</h2><p>Make accountability explicit and include the people who need project access.</p></div><label className="field-label">Owner<select className="modern-input" value={v.owner_id||""} onChange={e=>setV({...v,owner_id:e.target.value})}><option value="">Me / default owner</option>{ws?.users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><div className="field-label">Members<div className="member-picker">{ws?.users.map(u=><button type="button" key={u.id} className={v.member_ids.includes(u.id)?"member-pick selected":"member-pick"} onClick={()=>setV({...v,member_ids:v.member_ids.includes(u.id)?v.member_ids.filter(x=>x!==u.id):[...v.member_ids,u.id]})}><span>{u.name.charAt(0)}</span><div><strong>{u.name}</strong><small>{u.role}</small></div><i>{v.member_ids.includes(u.id)?'✓':''}</i></button>)}</div></div><div className="field-label">Project color<div className="color-picker">{colors.map(c=><button type="button" aria-label={`Choose ${c}`} key={c} className={v.color===c?'selected':''} style={{background:c}} onClick={()=>setV({...v,color:c})}/>)}</div></div><div className="project-form-tip"><strong>Why project health?</strong><p>Health is a management signal, separate from status. An active project can still be at risk before a deadline is missed.</p></div></aside></div><div className="form-submit-bar"><button type="button" className="secondary-btn" onClick={()=>history.back()}>Cancel</button><button className="primary-action" disabled={busy||!v.name.trim()}>{busy?'Saving…':submitLabel}</button></div></form>;
}
